import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import ThemeToggle from "../components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LTU Tab Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const studentNumber = "21993608";
  const studentName = "Steph Newland";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between items-center p-4 border-b border-gray-700">
          <div className="flex items-center gap-8">
            <span className="text-lg font-semibold">
              Student No: {studentNumber}
            </span>
            <nav className="flex gap-6 text-lg font-semibold tracking-wide">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/tabs">Tabs</Link>
              <Link href="/escape-room">Escape Room</Link>
              <Link href="/coding-races">Coding Races</Link>
              <Link href="/court-room">Court Room</Link>
            </nav>
          </div>
          <ThemeToggle />
        </header>

        <main className="flex flex-col min-h-screen">{children}</main>

        <footer className="p-4 border-t border-gray-700 text-center text-sm">
          © {new Date().getFullYear()} {studentName}, Student No:{" "}
          {studentNumber}, {new Date().toLocaleDateString()}
        </footer>
      </body>
    </html>
  );
}
